import {StyleSheet} from "react-native";
import {getColor} from "../../utils/ColorsParser";

export const bookDisplayScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: getColor('primaryColor'),
        padding: 20,
    },
    bookCoverContainer: {
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 16,
    },
    bookCover: {
        width: 140,
        height: 210,
        borderRadius: 12,
        backgroundColor: '#f0f0f0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 6,
    },
    bookTitleAuthor: {
        alignItems: 'center',
        marginBottom: 16,
    },
    bookTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#222',
        marginBottom: 4,
        textAlign: 'center',
    },
    bookAuthor: {
        fontSize: 16,
        color: '#666',
        marginBottom: 8,
        textAlign: 'center',
    },
    bookDescription: {
        flex: 1,
        marginBottom: 0,
        paddingHorizontal: 4,
        paddingRight: 16,
    },
    bookDescriptionText: {
        fontSize: 15,
        color: '#444',
        lineHeight: 23,
        textAlign: 'justify',
    },
    bookStats: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
        gap: 55,
        borderRadius:15,
        height: 50,
        backgroundColor: getColor('secondColor'),
    },
    bookStatItem: {
        alignItems: 'center',
        flexDirection: 'column',
        gap: 4,
    },
    bookStatDivider: {
        width: 1,
        height: 24,
        backgroundColor: '#DDD',
        marginHorizontal: 16,
        borderRadius: 1,
    },
    bookStatLabel: {
        fontSize: 13,
        color: '#888',
    },
    bookStatValue: {
        fontSize: 15,
        color: '#222',
        fontWeight: 'bold',
    },
    bookActions: {
        flexDirection: 'column',
        marginBottom: 10,
        gap: 12,
    },
    actionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    topRow: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginBottom: 8,
    },
    startReadButton: {
        flex: 1,
        backgroundColor: getColor('accent'),
        paddingVertical: 12,
        borderRadius: 10,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    rateButton: {
        flex: 1,
        backgroundColor: getColor('secondColor'),
        paddingVertical: 12,
        borderRadius: 10,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.18,
        shadowRadius: 4,
        elevation: 4,
    },
    addToLibButton: {
        width: 44,
        height: 44,
        backgroundColor: getColor('secondColor'),
        borderRadius: 22,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    actionButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    rateButtonText: {
        color: '#222',
        fontWeight: 'bold',
        fontSize: 16,
    },
    closeButton: {
        position: 'absolute',
        top: 16,
        right: 16,
        zIndex: 10,
        width: 36,
        height: 36,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0,0,0,0.08)',
        borderRadius: 18,
    },
    closeButtonText: {
        fontSize: 22,
        color: '#333',
        fontWeight: 'bold',
    },
});
